### ISSUE TITLE
Use the new graphcool framework

### ISSUE THREAD

**Issue by fabien0102** [fabien0102/climbing-app#13]
Actually it's a little bit messy and we don't have any information on policies.

The solution: the new graphcool framework (https://blog.graph.cool/graphcool-framework-preview-ff42081b1333)

## TODO
- [x] Init graphcool framework
- [x] Refactor functions/permissions
- [x] Add auth0
- [x] Add the crawler
- [x] Deploy all
- [x] Switch database in `/app`
- [x] Update auth process

## Tests
- [x] I can create a new user
- [x] I can navigate and add some tries
- [x] I can logout and login again (and retrieve my last tries)
- [x] Route stats are well updated

**Comment by fabien0102** [comment]
Waiting for https://github.com/graphcool/framework/issues/1031
